//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G5_Digital_Museum
{
    public partial class Guest_Gallery
    {
        protected global::System.Web.UI.WebControls.DataList dlGallery;
        protected global::System.Web.UI.WebControls.Label lblGalleryMsg;
    }
}
